### ISSUE TITLE
Debug output

### ISSUE THREAD

**Issue by DI3HARD139** [everamzah/dcb#14]
```
2016-07-15 20:29:35: WARNING[Main]: [xban] Unable to save database: Write failed
2016-07-15 20:29:35: ACTION[Main]: IRC: Disconnected.
2016-07-15 20:29:35: ACTION[Main]: [playereffects] Server shuts down. Rescuing data into playereffects.mt
2016-07-15 20:29:35: ACTION[Main]: [playereffects] Wrote playereffects data into /home/di3hard139/.minetest/worlds/AMHI[everamzah]/playereffects.mt.
[Thread 0x7fffe6f3b700 (LWP 26430) exited]
[Thread 0x7fffe5f39700 (LWP 26455) exited]
[Thread 0x7fffe532f700 (LWP 26456) exited]
2016-07-15 20:29:36: ERROR[Main]: ServerError: Lua: Runtime error from mod 'xdecor' in callback nodemeta_inventory_AllowPut(): ...i3hard139/.minetest/games/dcb/mods/xdecor/enchanting.lua:96: attempt to concatenate local 'tool' (a nil value)[Thread 0x7fffe7fff700 (LWP 26425) exited]
[Thread 0x7fffecd45700 (LWP 26424) exited]

2016-07-15 20:29:36: ERROR[Main]: stack traceback:
2016-07-15 20:29:36: ERROR[Main]: 	...i3hard139/.minetest/games/dcb/mods/xdecor/enchanting.lua:96: in function 'allowed'
2016-07-15 20:29:36: ERROR[Main]: 	...i3hard139/.minetest/games/dcb/mods/xdecor/enchanting.lua:106: in function <...i3hard139/.minetest/games/dcb/mods/xdecor/enchanting.lua:101>
[Thread 0x7fffce9d1700 (LWP 26594) exited]
[Thread 0x7fffe673a700 (LWP 26431) exited]
[Inferior 1 (process 26420) exited with code 01]
(gdb) 
```

**Comment by everamzah** [comment]
Interesting, but I still don't know.  There's no debugging information there, and I wonder why.  This is going to be a tough nut to crack.

**Comment by DI3HARD139** [comment]
Are there any customization done to xdecor or is it a Vanilla mod??

**Comment by everamzah** [comment]
It's part of X-Decor, and it in sync with https://github.com/minetest-mods/xdecor.  I added debug stuff, though, so it should show where it crashes.

**Comment by everamzah** [comment]
@DI3HARD139 I have pushed a new commit, which I hope will alleviate any crashes with the X-Decor enchantment table.  Let me know if it doesn't, with a fresh debug.txt.

**Comment by everamzah** [comment]
Wrong button.  ^_^

**Comment by DI3HARD139** [comment]
*bump*  Still experiencing random crashes. Gonna load into gdb to catch it.

**Comment by everamzah** [comment]
@DI3HARD139 Make sure you're on current HEAD if you submit a fresh debug.txt.  Last commit was four days ago.  Are you using an auto-update/auto-restart script?  The git repo uses submodules now, so that --recurse-submodules arg will come in handy, though you might need to clone fresh, I dunno.

**Comment by everamzah** [comment]
Doors were upgraded too, so that might add some additional CPU overhead while the old doors are converted, but not much.  Also, enchantment table shouldn't crash anymore, but in recent versions of DCB, debug.txt shows where the crash occurred and who initiated it.

**Comment by everamzah** [comment]
I also updated some other mods, like X-Decor's itemframe, so hopefully no issues pop up there.  The debug.txt will generally show what crashed, when it comes to a simple mod error.

Is the server still hanging?  I haven't seen it happen again since I last messaged you.

Good luck,
James

**Comment by DI3HARD139** [comment]
Updating now. Yeah I caught that the script wasn't updating correctly. Will have to revise it.

**Comment by DI3HARD139** [comment]
The most recent crash was due to the lua memory limitation that "caverealms" tends to hit from time to time.

**Comment by everamzah** [comment]
Whatever the case, enclosing the tail end of debug.txt inside three quotes
```
Like this.
```
Makes it easy to read, to see where the errors are.  Is minetestserver segfaulting and not logging any error?

**Comment by DI3HARD139** [comment]
Yeah for what reason logging of errors broke on 0.4.14. At least for crash related errors and some mod errors. Ill have to find out how VanessaE enabled Verbos mode. That will be super helpful. I've been using gdb to catch and freeze the outputs so I can post them here.

**Comment by everamzah** [comment]
Is `debug.txt` corrupt?  I would check minetest.conf for any settings that may have affected the log level.

**Comment by DI3HARD139** [comment]
I added "debug_log_level = verbose" to minetest.conf and started the server in GDB as a backup. Using a fresh debug.txt file atm. Just a heads up, "teleporters" is requiring that "deprecated_lua_api_handling " be set to "legacy" to prevent from crashing the moment a player joins. There may be more. I tried to set it to report to the log and the server went into a crash loop. I'll dig further into the API handling and logging of it.

**Comment by everamzah** [comment]
It would make sense to set `deprecated_lua_api_handling = legacy` in that case.  I'll look at the mod and see what I spot, but if you find the WARNING log entry, you can post that too.  Thanks.

**Comment by DI3HARD139** [comment]
Update: I'm currently working to implement a bot to log chat via IRC. I'm using rollback to monitor player actions. Logging has been switched to "Error" to keep from cluttering the file. 

Update 2: `2016-08-18 17:49:09: [Main]: Using world specified by --worldname on the command line
2016-08-18 17:49:10: [Main]: [TNT] Loaded!
2016-08-18 18:08:50: ERROR[Main]: ServerError: Lua: Runtime error from mod 'xdecor' in callback node_on_punch(): /usr/local/share/minetest/builtin/common/vector.lua:92: attempt to perform arithmetic on local 'b' (a nil value)
2016-08-18 18:08:50: ERROR[Main]: stack traceback:
2016-08-18 18:08:50: ERROR[Main]: 	/usr/local/share/minetest/builtin/common/vector.lua:92: in function 'add'
2016-08-18 18:08:50: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/falling.lua:137: in function 'check_attached_node'
2016-08-18 18:08:50: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/falling.lua:171: in function 'nodeupdate_single'
2016-08-18 18:08:50: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/falling.lua:220: in function 'nodeupdate'
2016-08-18 18:08:50: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/falling.lua:263: in function 'callback'
2016-08-18 18:08:50: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/item.lua:417: in function </usr/local/share/minetest/builtin/game/item.lua:410>
`

**Comment by DI3HARD139** [comment]
Update 3: `2016-08-21 05:18:37: [Main]: Using world specified by --worldname on the command line
2016-08-21 05:18:38: [Main]: [TNT] Loaded!
2016-08-21 05:53:44: ERROR[Server]: ServerEnv: Trying to store id=2956 statically but block (-79,1,-27) already contains 49 objects. Forcing delete.
2016-08-21 06:02:51: ERROR[Server]: 3d_armor: Detached armor inventory is nil [on_dieplayer]
2016-08-21 06:07:17: ERROR[Server]: Item "crops:corn" not defined`

Update 4: `2016-08-21 11:42:49: ERROR[Server]: 3d_armor: Detached armor inventory is nil [on_dieplayer]
2016-08-21 12:09:15: ERROR[Server]: Item "xdecor:stair_cobble" not defined`

Update 5: `2016-08-21 13:34:28: [Main]: Using world specified by --worldname on the command line
2016-08-21 13:34:29: [Main]: [TNT] Loaded!
2016-08-21 14:32:00: ERROR[Server]: 3d_armor: Detached armor inventory is nil [on_dieplayer]
2016-08-21 14:54:55: ERROR[Server]: 3d_armor: Detached armor inventory is nil [on_dieplayer]
2016-08-21 15:19:39: ERROR[Server]: 3d_armor: Detached armor inventory is nil [on_dieplayer]
2016-08-21 15:59:19: ERROR[Server]: 3d_armor: Detached armor inventory is nil [on_dieplayer]
2016-08-21 16:12:44: ERROR[Server]: ServerEnv: Trying to store id=14785 statically but block (-79,1,-27) already contains 49 objects. Forcing delete.
2016-08-21 16:12:45: ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=545 disconnecting peer!
2016-08-21 16:14:02: ERROR[Server]: ServerEnv: Trying to store id=14935 statically but block (-79,1,-27) already contains 49 objects. Forcing delete.
2016-08-21 16:14:16: ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=549 disconnecting peer!
2016-08-21 16:16:56: ERROR[Server]: ServerEnv: Trying to store id=15225 statically but block (-79,1,-27) already contains 49 objects. Forcing delete.
2016-08-21 16:16:57: ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=560 disconnecting peer!
2016-08-21 16:18:18: ERROR[Server]: ServerEnv: Trying to store id=15302 statically but block (-79,1,-27) already contains 49 objects. Forcing delete.
2016-08-21 16:18:19: ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=566 disconnecting peer!
2016-08-21 16:26:39: ERROR[Server]: ServerEnv: Trying to store id=16138 statically but block (-79,1,-27) already contains 49 objects. Forcing delete.
2016-08-21 16:28:35: ERROR[Server]: ServerEnv: Trying to store id=16330 statically but block (-79,1,-27) already contains 49 objects. Forcing delete.
2016-08-21 16:28:36: ERROR[Server]: Better HUD[error]: Not enough parameters given to change HUD item
2016-08-21 16:28:36: ERROR[Server]: 3d_armor: Player position is nil [set_player_armor]
2016-08-21 16:28:38: ERROR[Main]: ServerError: Runtime error from mod 'hud' in callback environment_Step(): /home/di3hard139/.minetest/games/dcb/mods/hud/builtin.lua:83: attempt to compare number with nil
2016-08-21 16:28:38: ERROR[Main]: stack traceback:
2016-08-21 16:28:38: ERROR[Main]: 	/home/di3hard139/.minetest/games/dcb/mods/hud/builtin.lua:83: in function 'func'
2016-08-21 16:28:38: ERROR[Main]: 	/home/di3hard139/.minetest/games/dcb/mods/hud/functions.lua:35: in function 'func'
2016-08-21 16:28:38: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/misc.lua:34: in function </usr/local/share/minetest/builtin/game/misc.lua:11>
2016-08-21 16:28:38: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/register.lua:369: in function </usr/local/share/minetest/builtin/game/register.lua:349>`

**Comment by everamzah** [comment]
Interesting stuff, thank you.

**Comment by DI3HARD139** [comment]
The newest completely random bug.

(gdb) --server --worldname AMHI[everamzah] --port 48258 --config /home/di3hard139/.minetest/AMHI_stuff/minetest.conf --logfile /home/di3hard139/.minetest/AMHI_stuff/debug.txt
Undefined command: "--server".  Try "help".
(gdb) run --server --worldname AMHI[everamzah] --port 48258 --config /home/di3hard139/.minetest/AMHI_stuff/minetest.conf --logfile /home/di3hard139/.minetest/AMHI_stuff/debug.txt
Starting program: /usr/local/bin/minetest --server --worldname AMHI[everamzah] --port 48258 --config /home/di3hard139/.minetest/AMHI_stuff/minetest.conf --logfile /home/di3hard139/.minetest/AMHI_stuff/debug.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
2016-10-04 17:24:26: [Main]: Using world specified by --worldname on the command line
[New Thread 0x7fffecba5700 (LWP 31755)]
[New Thread 0x7fffe7fff700 (LWP 31756)]
2016-10-04 17:24:26: WARNING[Main]: Mod name conflict detected: "mapfix"
2016-10-04 17:24:26: WARNING[Main]: Will not load: /home/di3hard139/.minetest/games/dcb/mods/mapfix
2016-10-04 17:24:26: WARNING[Main]: Overridden by: /home/di3hard139/.minetest/mods/mapfix
2016-10-04 17:24:26: WARNING[Main]: NodeDefManager: Ignoring CONTENT_IGNORE redefinition
[WorldEdit] Loaded!
2016-10-04 17:24:27: ACTION[Main]: [playereffects] playereffects.mt opened.
[Thread 0x7fffe7fff700 (LWP 31756) exited]
[Thread 0x7fffecba5700 (LWP 31755) exited]
2016-10-04 17:24:27: ERROR[Main]: ModError: Failed to load and run script from /home/di3hard139/.minetest/games/dcb/mods/playereffects/init.lua:
2016-10-04 17:24:27: ERROR[Main]: ...3hard139/.minetest/games/dcb/mods/playereffects/init.lua:58: attempt to index local 'savetable' (a nil value)
2016-10-04 17:24:27: ERROR[Main]: stack traceback:
2016-10-04 17:24:27: ERROR[Main]: 	...3hard139/.minetest/games/dcb/mods/playereffects/init.lua:58: in main chunk
[Inferior 1 (process 31742) exited with code 01]

`(gdb) --server --worldname AMHI[everamzah] --port 48258 --config /home/di3hard139/.minetest/AMHI_stuff/minetest.conf --logfile /home/di3hard139/.minetest/AMHI_stuff/debug.txt
Undefined command: "--server".  Try "help".
(gdb) run --server --worldname AMHI[everamzah] --port 48258 --config /home/di3hard139/.minetest/AMHI_stuff/minetest.conf --logfile /home/di3hard139/.minetest/AMHI_stuff/debug.txt
Starting program: /usr/local/bin/minetest --server --worldname AMHI[everamzah] --port 48258 --config /home/di3hard139/.minetest/AMHI_stuff/minetest.conf --logfile /home/di3hard139/.minetest/AMHI_stuff/debug.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
2016-10-04 17:24:26: [Main]: Using world specified by --worldname on the command line
[New Thread 0x7fffecba5700 (LWP 31755)]
[New Thread 0x7fffe7fff700 (LWP 31756)]
2016-10-04 17:24:26: WARNING[Main]: Mod name conflict detected: "mapfix"
2016-10-04 17:24:26: WARNING[Main]: Will not load: /home/di3hard139/.minetest/games/dcb/mods/mapfix
2016-10-04 17:24:26: WARNING[Main]: Overridden by: /home/di3hard139/.minetest/mods/mapfix
2016-10-04 17:24:26: WARNING[Main]: NodeDefManager: Ignoring CONTENT_IGNORE redefinition
[WorldEdit] Loaded!
2016-10-04 17:24:27: ACTION[Main]: [playereffects] playereffects.mt opened.
[Thread 0x7fffe7fff700 (LWP 31756) exited]
[Thread 0x7fffecba5700 (LWP 31755) exited]
2016-10-04 17:24:27: ERROR[Main]: ModError: Failed to load and run script from /home/di3hard139/.minetest/games/dcb/mods/playereffects/init.lua:
2016-10-04 17:24:27: ERROR[Main]: ...3hard139/.minetest/games/dcb/mods/playereffects/init.lua:58: attempt to index local 'savetable' (a nil value)
2016-10-04 17:24:27: ERROR[Main]: stack traceback:
2016-10-04 17:24:27: ERROR[Main]: 	...3hard139/.minetest/games/dcb/mods/playereffects/init.lua:58: in main chunk
[Inferior 1 (process 31742) exited with code 01]`

**Comment by everamzah** [comment]
No idea, as I haven't touched/changed anything in a long time.  It's been a much longer time since I have touched `playereffects`.  I can try some tests, and experiment to see if anything can be reproduced, but I'm at a loss right off.

**Comment by DI3HARD139** [comment]
Ok I found the problem for that. It was caused by either a corrupt playereffects.mt file or The size was too large for lua to handle.
